# Generated by Django 4.0.6 on 2022-07-19 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_uploadimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UploadImage',
        ),
    ]
