# Generated by Django 4.0.6 on 2022-07-19 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_delete_uploadimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctors',
            name='doc_img',
        ),
    ]
